# SPDX-FileCopyrightText: 2025-present jakub.szulc <szulcak05@gmail.com>
#
# SPDX-License-Identifier: MIT

from .autoresearch import run_autoresearch
from .data import NumeraiDataLoader
from .evaluation import (
    Backtester,
    EraSplitEvaluator,
    calculate_metrics,
    compute_ensemble_diagnostics,
    compute_feature_report,
    era_correlation_metrics,
    era_sharpe,
    era_sharpe_of_fnc,
    era_sharpe_of_mmc,
    evaluate_holdout_last_n_eras,
    fnc_score,
    mmc_score,
    payout_score,
    per_era_correlation,
    per_era_fnc,
    per_era_mmc,
    per_era_spearman,
    prepare_submission,
    rank_normalize,
    validate_submission,
)
from .hpo import (
    TrialResult,
    build_pipeline,
    build_pipeline_or_multi,
    ray_trainable,
    resolve_flat_config,
    run_trial,
    sample_random_config,
)
from .models import (
    BaseModel,
    CatBoostModel,
    LightGBMModel,
    ModelFactory,
    PackboostModel,
    SyntheticDataAugmenter,
    XGBoostModel,
)
from .pipeline import EnsembleOptimizer, FeatureNeutralizer, Pipeline, Stacker
from .preprocessors import (
    BasePreprocessor,
    EraStableFeatureSelector,
    GaussianNoiseInjector,
    GroupedPreprocessor,
    LGBMImportanceSelector,
    PackboostPreprocessor,
    PCAPreprocessor,
    PreprocessorFactory,
    RobustScalerPreprocessor,
    StandardScalerPreprocessor,
    TrainEvalPreprocessor,
    TruncatedSVDPreprocessor,
    VarianceFeatureSelector,
)
from .validation import PurgedEraCV

__all__ = [
    "Backtester",
    "BaseModel",
    "BasePreprocessor",
    "CatBoostModel",
    "EnsembleOptimizer",
    "EraSplitEvaluator",
    "EraStableFeatureSelector",
    "FeatureNeutralizer",
    "GaussianNoiseInjector",
    "GroupedPreprocessor",
    "LGBMImportanceSelector",
    "LightGBMModel",
    "ModelFactory",
    "NumeraiDataLoader",
    "PCAPreprocessor",
    "PackboostModel",
    "PackboostPreprocessor",
    "Pipeline",
    "PreprocessorFactory",
    "PurgedEraCV",
    "RobustScalerPreprocessor",
    "Stacker",
    "StandardScalerPreprocessor",
    "SyntheticDataAugmenter",
    "TrainEvalPreprocessor",
    "TrialResult",
    "TruncatedSVDPreprocessor",
    "VarianceFeatureSelector",
    "XGBoostModel",
    "build_pipeline",
    "build_pipeline_or_multi",
    "calculate_metrics",
    "compute_ensemble_diagnostics",
    "compute_feature_report",
    "era_correlation_metrics",
    "era_sharpe",
    "era_sharpe_of_fnc",
    "era_sharpe_of_mmc",
    "evaluate_holdout_last_n_eras",
    "fnc_score",
    "mmc_score",
    "payout_score",
    "per_era_correlation",
    "per_era_fnc",
    "per_era_mmc",
    "per_era_spearman",
    "prepare_submission",
    "rank_normalize",
    "ray_trainable",
    "resolve_flat_config",
    "run_autoresearch",
    "run_trial",
    "sample_random_config",
    "validate_submission",
]
